---

  - hosts: nodes
    become: yes
    become_user: root
    remote_user: centos

    tasks:
      - name: Synchronization
        copy:
          src: stack/exporters
          dest: "/opt/stack"
          owner: root
          group: root
          mode: 0644
        become: true

      - name: Up all services in compose
        command: docker-compose -f /opt/stack/exporters/docker-compose.exporters.yaml up -d
